INSERT INTO classes(id_class, class_name, class_symbol) VALUES(0, 'dot', 'dot');
INSERT INTO classes(id_class, class_name, class_symbol) VALUES(1, 'track', 'track');
INSERT INTO classes(id_class, class_name, class_symbol) VALUES(2, 'worm', 'worm');
INSERT INTO classes(id_class, class_name, class_symbol) VALUES(3, 'artefact', 'artefact');
SELECT setval('classes_id_class_seq', 3);

INSERT INTO classifier_types(id_classifier_type, classifier_type_name) VALUES(0, 'trigger');
INSERT INTO classifier_types(id_classifier_type, classifier_type_name) VALUES(1, 'four_class');
SELECT setval('classifier_types_id_classifier_type_seq', 1);

INSERT INTO classifiers(id_classifier_type, classifier_name, classifier_symbol) VALUES(0, 'anti-artefact', 'anti-artefact');
INSERT INTO classifiers(id_classifier_type, classifier_name, classifier_symbol) VALUES(0, 'CNN_small_w0', 'CNN_small_w0');
INSERT INTO classifiers(id_classifier_type, classifier_name, classifier_symbol) VALUES(0, 'CNN_big_w0', 'CNN_big_w0');
INSERT INTO classifiers(id_classifier_type, classifier_name, classifier_symbol) VALUES(0, 'CNN_small_w2', 'CNN_small_w2');
INSERT INTO classifiers(id_classifier_type, classifier_name, classifier_symbol) VALUES(0, 'CNN_big_w2', 'CNN_big_w2');
INSERT INTO classifiers(id_classifier_type, classifier_name, classifier_symbol) VALUES(0, 'CNN_small_w0_2', 'CNN_small_w0_2');
INSERT INTO classifiers(id_classifier_type, classifier_name, classifier_symbol) VALUES(0, 'CNN_big_w0_2', 'CNN_big_w0_2');
INSERT INTO classifiers(id_classifier_type, classifier_name, classifier_symbol) VALUES(0, 'CNN_small_w2_10', 'CNN_small_w2_10');
INSERT INTO classifiers(id_classifier_type, classifier_name, classifier_symbol) VALUES(0, 'CNN_big_w2_10', 'CNN_big_w2_10');
INSERT INTO classifiers(id_classifier_type, classifier_name, classifier_symbol) VALUES(0, 'CNN_small_w20', 'CNN_small_w20');
INSERT INTO classifiers(id_classifier_type, classifier_name, classifier_symbol) VALUES(0, 'CNN_big_w20', 'CNN_big_w20');
INSERT INTO classifiers(id_classifier_type, classifier_name, classifier_symbol) VALUES(0, 'CNN_small_w2_20', 'CNN_small_w2_20');
INSERT INTO classifiers(id_classifier_type, classifier_name, classifier_symbol) VALUES(0, 'CNN_big_w2_20', 'CNN_big_w2_20');
INSERT INTO classifiers(id_classifier_type, classifier_name, classifier_symbol) VALUES(0, 'CNN_small_raw', 'CNN_small_raw');
INSERT INTO classifiers(id_classifier_type, classifier_name, classifier_symbol) VALUES(0, 'CNN_big_raw', 'CNN_big_raw');
INSERT INTO classifiers(id_classifier_type, classifier_name, classifier_symbol) VALUES(0, 'baseline', 'baseline');
INSERT INTO classifiers(id_classifier_type, classifier_name, classifier_symbol) VALUES(0, 'baseline_knn', 'baseline_knn');
INSERT INTO classifiers(id_classifier_type, classifier_name, classifier_symbol) VALUES(0, 'baseline_rf', 'baseline_rf');
INSERT INTO classifiers(id_classifier_type, classifier_name, classifier_symbol) VALUES(1, 'etc', 'etc');
INSERT INTO classifiers(id_classifier_type, classifier_name, classifier_symbol) VALUES(1, 'bagsvc', 'bagsvc');
INSERT INTO classifiers(id_classifier_type, classifier_name, classifier_symbol) VALUES(1, 'gbc', 'gbc');
INSERT INTO classifiers(id_classifier_type, classifier_name, classifier_symbol) VALUES(1, 'knn', 'knn');
INSERT INTO classifiers(id_classifier_type, classifier_name, classifier_symbol) VALUES(1, 'mlp', 'mlp');
INSERT INTO classifiers(id_classifier_type, classifier_name, classifier_symbol) VALUES(1, 'nsv', 'nsv');
INSERT INTO classifiers(id_classifier_type, classifier_name, classifier_symbol) VALUES(1, 'ovo_mlp', 'ovo_mlp');
INSERT INTO classifiers(id_classifier_type, classifier_name, classifier_symbol) VALUES(1, 'ovo_svm', 'ovo_svm');
INSERT INTO classifiers(id_classifier_type, classifier_name, classifier_symbol) VALUES(1, 'ovr_mlp', 'ovr_mlp');
INSERT INTO classifiers(id_classifier_type, classifier_name, classifier_symbol) VALUES(1, 'rf', 'rf');
INSERT INTO classifiers(id_classifier_type, classifier_name, classifier_symbol) VALUES(1, 'svm', 'svm');
INSERT INTO classifiers(id_classifier_type, classifier_name, classifier_symbol) VALUES(1, 'vot', 'vot');
